---
name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        version:
          - 'cp38-cp38'
          - 'cp39-cp39'
          - 'cp310-cp310'
          - 'cp311-cp311'
          - 'cp312-cp312'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          docker build -t builder .
      - name: Run
        run: |
          curl -J -O -L 'https://pypi.io/packages/source/z/zeroc-ice/zeroc-ice-3.6.5.tar.gz'
          tar zxf zeroc-ice-3.6.5.tar.gz
          for f in patches/*; do patch -p0 < ${f}; done
          docker run --rm -v $PWD/zeroc-ice-3.6.5:/build builder /bin/bash -c "cd /build ; /opt/python/${{ matrix.version }}/bin/python setup.py build -j 3"
          docker run --rm -v $PWD/zeroc-ice-3.6.5:/build builder /bin/bash -c "cd /build ; /opt/python/${{ matrix.version }}/bin/python setup.py bdist_wheel"
          docker run --rm -v $PWD/zeroc-ice-3.6.5:/build builder auditwheel repair --plat 'manylinux_2_28_x86_64' -w /build/dist /build/dist/zeroc_ice-3.6.5-${{ matrix.version }}-linux_x86_64.whl
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: zeroc-ice-3.6.5/dist/*manylinux*.whl
          if-no-files-found: error
  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from build
        uses: actions/download-artifact@v3
      - name: List artifacts
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*.whl
